all:
  hosts:
    cp1:
      ansible_host: 158.160.8.69
      ansible_user: yc-user
    node1:
      ansible_host: 158.160.10.80
      ansible_user: yc-user
    node2:
      ansible_host: 158.160.10.39
      ansible_user: yc-user
    node3:
      ansible_host: 158.160.7.135
      ansible_user: yc-user
    node4:
      ansible_host: 51.250.31.31
      ansible_user: yc-user
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
